- id: grok_new_entity_automation
  alias: Détection de nouvelle entité pour Grok Suggestions
  description: Déclenche la génération de suggestions lorsqu’une nouvelle entité est détectée.
  trigger:
    - platform: event
      event_type: entity_registry_updated
      event_data:
        action: create
  action:
    - service: system_log.write
      data:
        message: "Nouvelle entité détectée, lancement des suggestions Grok"
        level: info
    - service: grok_automation_suggester.generate_suggestions
      data:
        all_entities: false
    - condition: "{{ not is_state('sensor.grok_automation_suggestions', 'No suggestions') }}"
      service: notify.persistent_notification
      data:
        title: "Nouvelles suggestions d’automatisation Grok"
        message: "Consultez sensor.grok_automation_suggestions pour les détails."
