name: Validate with hassfest and HACS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # Compatible with recent Home Assistant versions

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant==2024.1.0  # Match version in hacs.json
          pip install hacs

      - name: Verify Home Assistant installation
        run: |
          python -c "import homeassistant; print('Home Assistant version:', homeassistant.__version__)"

      - name: Run hassfest validation
        run: |
          python -m script.hassfest

      - name: Run HACS validation
        run: |
          python -m hacs validate
