name: Validate with hassfest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant
      - name: Run hassfest validation
        run: |
          python -m script.hassfest
      - name: Check HACS compatibility
        run: |
          pip install hacs
          python -m hacs validate
